"""
Django settings for resource_share_platform project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rb%mw#64*l2$h=1x%ixb@%yrh(hrv89#dvs(xg6e^oii4ly#f$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'resources',
    'rest_framework',
    'django.contrib.sites',  # 添加站点支持
    'allauth',               # 添加 allauth 支持
    'allauth.account',
    'allauth.socialaccount',
    'profiles',
    'comments.apps.CommentsConfig',  # 使用配置类
]



# 定义站点ID，通常用于多站点配置中标识当前站点
SITE_ID = 1

# 配置认证后端，指定Django使用的认证后端类
# 默认使用Django的ModelBackend进行认证
# 同时使用allauth的AuthenticationBackend进行额外的认证处理
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# 配置登录后的重定向URL，用户登录成功后将被重定向到根路径'/'
LOGIN_REDIRECT_URL = '/'

# 配置登出后的重定向URL，用户登出后将被重定向到登录页面'/accounts/login/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# 配置账户相关设置

# 要求用户在注册时必须提供电子邮件地址
ACCOUNT_EMAIL_REQUIRED = True

# 允许用户在注册时不提供用户名
ACCOUNT_USERNAME_REQUIRED = False

# 指定认证方式为电子邮件，用户将使用电子邮件地址进行登录
# ACCOUNT_AUTHENTICATION_METHOD = 'email'

ACCOUNT_LOGIN_METHODS = {'email'}

# 启用会话记住功能，用户登录后可以选择记住登录状态
ACCOUNT_SESSION_REMEMBER = True

# 允许用户通过GET请求直接登出，而不需要POST请求
ACCOUNT_LOGOUT_ON_GET = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'resource_share_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'resource_share_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'resource_share_db',
        'USER': 'root',
        'PASSWORD': '123321',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]